version: "3.8"

services:
    bot:
        container_name: bot
        ports: 
            - "9000:9000"
        build:
            context: .
            dockerfile: ./build/Dockerfile-bot

    godoc:
        container_name: godoc
        ports:
            - "6060:6060"
        build: 
            context: .
            dockerfile: ./build/Dockerfile-godoc

volumes:
    db-data: